changed formatting
GeoScripting-WUR/PythonRaster pull request #8
Opened 2023-08-27 08:52 UTC by elikreuz

@GreatEmerald

2023-08-28 07:44 UTC, GreatEmerald requested changes
Thanks, one minor point below.

2023-08-28 07:44 UTC, GreatEmerald commented on index.Rmd
> +<center>
This is not a closing tag now, since you forgot a `/`.

2023-10-01 06:28 UTC, elikreuz commented
@GreatEmerald I changed the links to the WCS because they were not working, and also changed how the building were loaded in with GeoPandas and requests, since the previous exercise they used a different method (and again the link for buildings was giving errors.

2023-10-02 09:28 UTC, GreatEmerald commented
Thanks!

2023-10-02 09:28 UTC, GreatEmerald approved these changes

2023-10-02 09:28 UTC, merged